CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250422085653_InitUsers') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "FirstName" text,
        "Phone" text,
        "LastName" text,
        "Email" text,
        "PhotoUrl" bytea,
        "Details" jsonb,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250422085653_InitUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250422085653_InitUsers', '8.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250428060452_AddGoodsTable') THEN
    CREATE TABLE "Goods" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        description text NOT NULL,
        CONSTRAINT "PK_Goods" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250428060452_AddGoodsTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250428060452_AddGoodsTable', '8.0.2');
    END IF;
END $EF$;
COMMIT;

