START TRANSACTION;

CREATE TABLE "UserProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdentityUserId" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserProfiles_AspNetUsers_IdentityUserId" FOREIGN KEY ("IdentityUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserProfiles_IdentityUserId" ON "UserProfiles" ("IdentityUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250503051818_AddUserProfile', '8.0.2');

COMMIT;

